### ISSUE TITLE
构造where条件表达式执行报错

### ISSUE THREAD

**Issue by panda-big** [shuxinqin/Chloe#209]
`if (!string.IsNullOrEmpty(equipmentName))
            {
                var where = PredicateExtensions.True<TaskSearchModel>();
                var words = equipmentName.Trim().ToArray();
                foreach (var word in words)
                {
                    where = where.And(s => s.EquipmentName.Contains(word));
                }
                queries = queries.Where(where);
            }`

![image](https://user-images.githubusercontent.com/49589838/97133509-43c4eb00-1785-11eb-9960-6062db5b038a.png)

`public static class PredicateExtensions
	{
		public static Expression<Func<T, bool>> True<T>() { return f => true; }

		public static Expression<Func<T, bool>> False<T>() { return f => false; }

		public static Expression<Func<T, bool>> Or<T>(this Expression<Func<T, bool>> expression1,
		   Expression<Func<T, bool>> expression2)
		{
			var invokedExpression = Expression.Invoke(expression2, expression1.Parameters
					.Cast<Expression>());

			return Expression.Lambda<Func<T, bool>>(Expression.Or(expression1.Body, invokedExpression),
			expression1.Parameters);
		}

		public static Expression<Func<T, bool>> And<T>(this Expression<Func<T, bool>> expression1,
			  Expression<Func<T, bool>> expression2)
		{
			var invokedExpression = Expression.Invoke(expression2, expression1.Parameters
				 .Cast<Expression>());

			return Expression.Lambda<Func<T, bool>>(Expression.And(expression1.Body,
				   invokedExpression), expression1.Parameters);
		}
	}`

构造where条件表达式报错：
Unhandled expression type: 'Invoke'
`at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Specific(Expression exp, Boolean trueOrFalse)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal_Boolean(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_AndAlso(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_And(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Specific(Expression exp, Boolean trueOrFalse)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal_Boolean(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_AndAlso(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_And(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Specific(Expression exp, Boolean trueOrFalse)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal_Boolean(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitBinary_Equal(BinaryExpression exp)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Core.Visitors.ExpressionVisitorBase.VisitLambda(LambdaExpression lambda)
   at Chloe.Query.Visitors.GeneralExpressionParser.VisitLambda(LambdaExpression lambda)
   at Chloe.Core.Visitors.ExpressionVisitor`1.Visit(Expression exp)
   at Chloe.Query.Visitors.GeneralExpressionParser.Parse(Expression exp, ScopeParameterDictionary scopeParameters, StringSet scopeTables)
   at Chloe.Query.Visitors.FilterPredicateParser.Parse(LambdaExpression filterPredicate, ScopeParameterDictionary scopeParameters, StringSet scopeTables)
   at Chloe.Query.QueryState.QueryStateBase.Accept(WhereExpression exp)
   at Chloe.Query.Visitors.QueryExpressionResolver.Visit(WhereExpression exp)
   at Chloe.Query.QueryExpressions.WhereExpression.Accept[T](QueryExpressionVisitor`1 visitor)
   at Chloe.Query.Visitors.QueryExpressionResolver.Visit(GroupingQueryExpression exp)
   at Chloe.Query.QueryExpressions.GroupingQueryExpression.Accept[T](QueryExpressionVisitor`1 visitor)
   at Chloe.Query.Visitors.QueryExpressionResolver.Visit(OrderExpression exp)
   at Chloe.Query.QueryExpressions.OrderExpression.Accept[T](QueryExpressionVisitor`1 visitor)
   at Chloe.Query.Visitors.QueryExpressionResolver.Visit(SkipExpression exp)
   at Chloe.Query.QueryExpressions.SkipExpression.Accept[T](QueryExpressionVisitor`1 visitor)
   at Chloe.Query.Visitors.QueryExpressionResolver.Visit(TakeExpression exp)
   at Chloe.Query.QueryExpressions.TakeExpression.Accept[T](QueryExpressionVisitor`1 visitor)
   at Chloe.Query.Visitors.QueryExpressionResolver.Resolve(QueryExpression queryExpression, ScopeParameterDictionary scopeParameters, StringSet scopeTables)
   at Chloe.Query.Internals.InternalQuery`1.GenerateCommandFactor()
   at Chloe.Query.Internals.InternalQuery`1.GetEnumerator()
   at Chloe.Query.Internals.InternalQuery`1.ExecuteAsync()
   at Chloe.Query.Query`1.GenerateIteratorAsync()`

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/AceBlog/blob/master/src/DotNetEx/Extensions/ExpressionExtension.cs
用这个构建

**Comment by panda-big** [comment]
我后面解决了，我直接集成一个表达式类封装到扩展库里去吧！我看很多人都有这个需求，我刚好写个，你觉得呢?

**Comment by shuxinqin** [comment]
出现上述问题是因为构建lambda表达式树不规范。
