### ISSUE TITLE
.net 5发布到centos后连接sqlserver超时,在本地正常，其他版本在liunx下也正常

### ISSUE THREAD

**Issue by FreeTimeWorker** [shuxinqin/Chloe#232]
.net 版本 .net5  chloe.sqlserver版本 4.9.0

```
 <ItemGroup>
    <PackageReference Include="chloe.sqlserver" Version="4.9.0" />
  </ItemGroup>
```
代码非常简单

```
 public IActionResult Index()
        {
            MsSqlContext msSqlContext = new MsSqlContext(_configuration["SqlConnectionString"]);
            ViewBag.UserName = msSqlContext.Query<SysUser>().FirstOrDefault().UserName;
            return View();
        }
```
![image](https://user-images.githubusercontent.com/13743422/104707364-436e3780-5757-11eb-8c6d-d65e3973bbef.png)
![image](https://user-images.githubusercontent.com/13743422/104707411-5254ea00-5757-11eb-8ac2-04cb9e0e8c3d.png)

错误的详细信息：
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Timeout expired.  The timeout period elaps                                                                          ed prior to obtaining a connection from the pool.  This may have occurred because                                                                           all pooled connections were in use and max pool size was reached.
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnec                                                                          tion owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptio                                                                          ns, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInterna                                                                          l(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskComplet                                                                          ionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnec                                                                          tion outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`                                                                          1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 ret                                                                          ry)
         at System.Data.SqlClient.SqlConnection.Open()
         at System.Data.AdoExtension.Open(IDbConnection conn, Boolean async)
         at Chloe.Data.AdoSession.Activate(Boolean async)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] paramete                                                                          rs, CommandType cmdType, CommandBehavior behavior, Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](Task`1 task)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] paramete                                                                          rs, CommandType cmdType, CommandBehavior behavior)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] paramete                                                                          rs, CommandType cmdType)
         at Chloe.Data.InnerAdoSession.ExecuteReader(String cmdText, DbParam[] par                                                                          ameters, CommandType cmdType)
         at Chloe.Core.DbSession.ExecuteReader(String cmdText, CommandType cmdType                                                                          , DbParam[] parameters)
         at Chloe.DbSessionExtension.ExecuteReader(IDbSession dbSession, String cm                                                                          dText, CommandType cmdType, DbParam[] parameters, Boolean async)
         at Chloe.Query.Internals.InternalQuery`1.<GetEnumerator>b__3_0(DbCommandF                                                                          actor cmdFactor, Boolean async)
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext(Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](ValueTask`1 tas                                                                          k)
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Bool                                                                          ean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
         at Chloe.Query.Query`1.FirstOrDefault()
         at test.Controllers.HomeController.Index() in F:\代码垃圾堆\test\Controll                                                                          ers\HomeController.cs:line 28
         at lambda_method1(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActio                                                                          nResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor execu                                                                          tor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Invoke                                                                          ActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(S                                                                          tate& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Invoke                                                                          NextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethro                                                                          w(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(S                                                                          tate& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Invoke                                                                          InnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextRes                                                                          ourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Sc                                                                          ope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(Resour                                                                          ceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& ne                                                                          xt, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPi                                                                          pelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g                                                                          __Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitReques                                                                          tTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(Http                                                                          Context context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g_                                                                          _Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task 

已经确定数据库可连接，sqlserver版本号2012，同一个服务器的另外一个项目也是用的chloe.orm，.net core 版本3.1

**Comment by shuxinqin** [comment]
用什么驱动？
用这个试试 Microsoft.Data.SqlClient
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/Chloe.SqlServer.csproj#L42

**Comment by FreeTimeWorker** [comment]
> 用什么驱动？
> 用这个试试 Microsoft.Data.SqlClient
> https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/Chloe.SqlServer.csproj#L42

我尝试把.net 5降到.net core 3.1 后正常了

**Comment by shuxinqin** [comment]
试着手动new 一个dbconnection连接数据库试试，看下驱动有没有问题

**Comment by FreeTimeWorker** [comment]
> 试着手动new 一个dbconnection连接数据库试试，看下驱动有没有问题

驱动确实有问题，我看到 4.9.0所依赖的System.Data.SqlClient在.net5的环境下连接会有问题,

 SqlConnection sqlConnection = new SqlConnection(_configuration["SqlConnectionString"]);
            sqlConnection.Open();
            ViewBag.UserName = "连接成功";

错误和刚才一样

**Comment by FreeTimeWorker** [comment]
> 试着手动new 一个dbconnection连接数据库试试，看下驱动有没有问题

 System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)

**Comment by shuxinqin** [comment]
我有空再发布个chloe.sqlserver版本，你先手动引用chloe和chloe.sqlserver源码到你项目里先吧吧

**Comment by shuxinqin** [comment]
最新源码在net5下编译用的是 Microsoft.Data.SqlClient驱动

**Comment by FreeTimeWorker** [comment]
> 最新源码在net5下编译用的是 Microsoft.Data.SqlClient驱动

感谢大神，虽然也曾经捐赠了一点，但是第一次近距离和大神沟通，心情不免激动，希望这个项目可以持续做下去，在下收益匪浅，再次表示感谢

**Comment by shuxinqin** [comment]
.net5 下的Chloe.SqlServer包已经发布，直接nuget安装即可。

**Comment by FreeTimeWorker** [comment]
> .net5 下的Chloe.SqlServer包已经发布，直接nuget安装即可。

今天把程序从core3.1升级到net5.0，后引用了新包，重新发布后出现了另外一个错误
![image](https://user-images.githubusercontent.com/13743422/104981830-54af9080-5a44-11eb-96b3-cc6c50808276.png)
 Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM5S4GP0519B", Request id "0HM5S4GP0519B:00000005": An unhandled exception was thrown by the application.
      Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
       ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
         at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
         at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
         at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
         at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
         at Microsoft.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle handle, UInt32 options)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
         at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
         at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
         at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
         at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
         at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
         at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
         at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
         at Microsoft.Data.SqlClient.SqlConnection.Open()
         at System.Data.AdoExtension.Open(IDbConnection conn, Boolean async)
         at Chloe.Data.AdoSession.Activate(Boolean async)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior, Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](Task`1 task)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
         at Chloe.Data.InnerAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
         at Chloe.Core.DbSession.ExecuteReader(String cmdText, CommandType cmdType, DbParam[] parameters)
         at Chloe.DbSessionExtension.ExecuteReader(IDbSession dbSession, String cmdText, CommandType cmdType, DbParam[] parameters, Boolean async)
         at Chloe.Query.Internals.InternalQuery`1.<GetEnumerator>b__3_0(DbCommandFactor cmdFactor, Boolean async)
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext(Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](ValueTask`1 task)
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Chloe.Query.Query`1.ToList()
         at LORD.MONITOR.Service.ServiceUser.Login(String userName, String passWord, String& message) in E:\Jenkins\workspace\监管平台Linux\source\LORD.MONITOR.Service\ServiceUser.cs:line 34
         at LORD.MONITOR.Web.Controllers.LoginController.ConfirmUserToken(ViewModelUserToken formCollection) in E:\Jenkins\workspace\监管平台Linux\source\LORD.MONITOR.Web\Controllers\LoginController.cs:line 58
         at lambda_method15(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
      ClientConnectionId:78ee33b9-e911-4492-a496-06fd516e82b0

貌似是System.Net.Security这个类库再.net5下有一些不一样的地方，导致的异常

**Comment by shuxinqin** [comment]
这个异常看起来不是Chloe的问题。这个你得从驱动，连接字符串等其他方面排查问题了。如果需要更换驱动，只需要创建MsSqlContext对象时传入 IDbConnectionFactory 对象即可 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlContext.cs#L36
IDbConnectionFactory 实现参考 http://www.52chloe.com/Wiki/Document/3325145866628497408

**Comment by kygl** [comment]
你的sql server是哪个版本？linux dotnet的sql server只支持sql2012或以上
