### ISSUE TITLE
V4.1.0 版本 Oracle更新查询 生成的的参数个数不对？？？

### ISSUE THREAD

**Issue by yangzhinong** [shuxinqin/Chloe#262]
生成的需要插入字段是全部（除了主键的2个外的所有列52个），而不是变动的， 并且与最后的参数个（:P0-:P3)只有31个）是我使用方法不对么？ 生成的命令行文本是： 

INSERT INTO "YZN"."INSUR_VISIT_RECORD"("PATIENT_ID","VISIT_ID","INSUR_TYPE","INSUR_NO","CENTER_CODE","ADMIT_NO","ADMIT_INSUR_TYPE","ADMIT_MED_TYPE","ADMIT_DATE","ADMIT_DEPT_CODE","ADMIT_DEPT_NAME","ADMIT_DISE_CODE","ADMIT_DISE_NAME","ADMIT_BED_NO","ADMIT_DOCTOR_CODE","ADMIT_DOCTOR_NAME","ADMIT_TRADE_NO","ADMIT_TRADE_DATE","ADMIT_OPERID","BIRTH_BABYS","BIRTH_OPERATION","BIRTH_COMP","HUSBAND_IDNO","HUSBAND_NAME","SETTLE_NO","TOTAL_MONEY","CASH_PAY","FUND_PAY","ACCOUNT_PAY","CIVILSERVAN_SUBSIDY","MEDICAID_PAY","LARGE_PAY","ACCOUNT_BALANCE","DIS_DEPT_CODE","DIS_DEPT_NAME","DIS_DISE_CODE","DIS_DISE_NAME","DIS_DATE","SETTLE_TRADE_NO","SETTLE_TRADE_DATE","SETTLE_OPERID","EXTEND1","EXTEND2","EXTEND3","EXTEND4","EXTEND5","CARD_TYPE","CARD_NO","INSUR_STATUS","BILL_UPLOAD","DIS_WAY","ADMIT_WAY","SETTLE_TRADE_DATE_END","HI_PAYMTD") VALUES(:P_0,:P_1,:P_2,:P_3,:P_4,:P_5,:P_6,:P_7,:P_8,:P_9,:P_10,:P_11,:P_12,:P_13,:P_13,:P_13,:P_13,:P_14,:P_15,:P_16,:P_13,:P_13,:P_13,:P_13,:P_17,:P_18,:P_19,:P_20,:P_19,:P_19,:P_19,:P_19,:P_21,:P_22,:P_23,:P_11,:P_12,:P_24,:P_13,:P_25,:P_26,:P_13,:P_13,:P_13,:P_13,:P_13,:P_27,:P_28,:P_29,:P_13,:P_30,:P_31,:P_32,:P_30)

代码如下：
                var d = db.Query<Models.Insur_Visit_Record>().FirstOrDefault();
                db.TrackEntity(d);
                d.Settle_No = "1231";
                d.Settle_Operid = "123";
                d.Account_Pay = 0m;
                d.Cash_Pay = 0m;
                d.Total_Money = 250.12m;
                d.Settle_Trade_Date = DateTime.Now;
                d.Settle_Trade_Date_End = DateTime.Now.AddMinutes(1);
                d.Insur_Status = "已核实";
                d.Account_Balance = 20;
                db.Save(d);

----表脚本是---
CREATE TABLE YZN.INSUR_VISIT_RECORD
(
  PATIENT_ID             VARCHAR2(20 BYTE)      NOT NULL,
  VISIT_ID               NUMBER(4)              NOT NULL,
  INSUR_TYPE             VARCHAR2(20 BYTE),
  INSUR_NO               VARCHAR2(30 BYTE),
  CENTER_CODE            VARCHAR2(20 BYTE),
  ADMIT_NO               VARCHAR2(30 BYTE),
  ADMIT_INSUR_TYPE       VARCHAR2(20 BYTE),
  ADMIT_MED_TYPE         VARCHAR2(20 BYTE),
  ADMIT_DATE             DATE,
  ADMIT_DEPT_CODE        VARCHAR2(20 BYTE),
  ADMIT_DEPT_NAME        VARCHAR2(50 BYTE),
  ADMIT_DISE_CODE        VARCHAR2(50 BYTE),
  ADMIT_DISE_NAME        VARCHAR2(150 BYTE),
  ADMIT_BED_NO           VARCHAR2(20 BYTE),
  ADMIT_DOCTOR_CODE      VARCHAR2(20 BYTE),
  ADMIT_DOCTOR_NAME      VARCHAR2(60 BYTE),
  ADMIT_TRADE_NO         VARCHAR2(50 BYTE),
  ADMIT_TRADE_DATE       DATE,
  ADMIT_OPERID           VARCHAR2(8 BYTE),
  BIRTH_BABYS            NUMBER(1),
  BIRTH_OPERATION        VARCHAR2(50 BYTE),
  BIRTH_COMP             VARCHAR2(50 BYTE),
  HUSBAND_IDNO           VARCHAR2(20 BYTE),
  HUSBAND_NAME           VARCHAR2(60 BYTE),
  SETTLE_NO              VARCHAR2(30 BYTE),
  TOTAL_MONEY            NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  CASH_PAY               NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  FUND_PAY               NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  ACCOUNT_PAY            NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  CIVILSERVAN_SUBSIDY    NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  MEDICAID_PAY           NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  LARGE_PAY              NUMBER(18,4)           DEFAULT (0)                   NOT NULL,
  ACCOUNT_BALANCE        NUMBER(12,2)           DEFAULT (0)                   NOT NULL,
  DIS_DEPT_CODE          VARCHAR2(20 BYTE),
  DIS_DEPT_NAME          VARCHAR2(50 BYTE),
  DIS_DISE_CODE          VARCHAR2(50 BYTE),
  DIS_DISE_NAME          VARCHAR2(150 BYTE),
  DIS_DATE               DATE,
  SETTLE_TRADE_NO        VARCHAR2(50 BYTE),
  SETTLE_TRADE_DATE      DATE,
  SETTLE_OPERID          VARCHAR2(8 BYTE),
  EXTEND1                VARCHAR2(50 BYTE),
  EXTEND2                VARCHAR2(50 BYTE),
  EXTEND3                VARCHAR2(200 BYTE),
  EXTEND4                VARCHAR2(200 BYTE),
  EXTEND5                VARCHAR2(50 BYTE),
  CARD_TYPE              VARCHAR2(20 BYTE),
  CARD_NO                VARCHAR2(50 BYTE),
  INSUR_STATUS           VARCHAR2(20 BYTE),
  BILL_UPLOAD            VARCHAR2(30 BYTE),
  DIS_WAY                VARCHAR2(20 BYTE),
  ADMIT_WAY              VARCHAR2(20 BYTE),
  SETTLE_TRADE_DATE_END  DATE,
  HI_PAYMTD              VARCHAR2(20 BYTE)
)
CREATE UNIQUE INDEX YZN.INSUR_VISIT_RECORD_PK ON YZN.INSUR_VISIT_RECORD
(PATIENT_ID, VISIT_ID)；

SET DEFINE OFF;
Insert into SYSTEM.INSUR_VISIT_RECORD
   (PATIENT_ID, VISIT_ID, INSUR_TYPE, INSUR_NO, CENTER_CODE, 
    ADMIT_NO, ADMIT_INSUR_TYPE, ADMIT_MED_TYPE, ADMIT_DATE, ADMIT_DEPT_CODE, 
    ADMIT_DEPT_NAME, ADMIT_DISE_CODE, ADMIT_DISE_NAME, ADMIT_TRADE_DATE, ADMIT_OPERID, 
    SETTLE_NO, TOTAL_MONEY, CASH_PAY, FUND_PAY, ACCOUNT_PAY, 
    CIVILSERVAN_SUBSIDY, MEDICAID_PAY, LARGE_PAY, ACCOUNT_BALANCE, DIS_DEPT_CODE, 
    DIS_DEPT_NAME, DIS_DISE_CODE, DIS_DISE_NAME, SETTLE_TRADE_DATE, SETTLE_OPERID, 
    CARD_TYPE, CARD_NO, INSUR_STATUS, DIS_WAY, ADMIT_WAY, 
    SETTLE_TRADE_DATE_END, HI_PAYMTD)
 Values
   ('10002000', 2, '市医保', '61CS0006110001197503070008', '610602', 
    '288192', '310', '21', TO_DATE('08/19/2021 14:48:16', 'MM/DD/YYYY HH24:MI:SS'), 'A03', 
    '内科', 'U07.100x002', '新型冠状病毒感染', TO_DATE('08/19/2021 17:08:08', 'MM/DD/YYYY HH24:MI:SS'), '0006', 
    '273059', 390, 0, 390, 39, 
    0, 0, 0, 2581.78, 'A03.03', 
    '神经内科专业', 'U07.100x002', '新型冠状病毒感染', TO_DATE('08/25/2021 16:03:32', 'MM/DD/YYYY HH24:MI:SS'), '0006', 
    '02', '610302194904050539', '已结算', '1', '2', 
    TO_DATE('08/25/2021 16:03:32', 'MM/DD/YYYY HH24:MI:SS'), '1');
COMMIT;

---实体实本是----
/// <summary>
    /// 医保住院记录
    /// </summary>
    [Table("INSUR_VISIT_RECORD", "YZN")]
    public partial class Insur_Visit_Record
    {
        /// <summary>
        /// 病人ID
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=0
        /// </summary>
        [Column(IsPrimaryKey = true)]
        public string Patient_Id { get; set; }

        /// <summary>
        /// 院次
        /// DataType=NUMBER
        /// 精度=(4,0)
        /// Nullable=0
        /// </summary>
        [Column(IsPrimaryKey = true)]
        public int Visit_Id { get; set; }

        /// <summary>
        /// 医保类别
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Insur_Type { get; set; }

        /// <summary>
        /// 医保人个编码
        /// DataType=VARCHAR2
        /// 长度=30
        /// Nullable=1
        /// </summary>
        public string Insur_No { get; set; }

        /// <summary>
        /// 医保中心编号(病人的参保地编码)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Center_Code { get; set; }

        /// <summary>
        /// 医保登记号(登记上传后,医保返回的)
        /// DataType=VARCHAR2
        /// 长度=30
        /// Nullable=1
        /// </summary>
        public string Admit_No { get; set; }

        /// <summary>
        /// 本次险种类别(工伤,医疗等)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Insur_Type { get; set; }

        /// <summary>
        /// 医保医疗类别(门诊,住院,生育等)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Med_Type { get; set; }

        /// <summary>
        /// 入院时间
        /// DataType=DATE
        /// Nullable=1
        /// </summary>
        public DateTime? Admit_Date { get; set; }

        /// <summary>
        /// 入院科室编码(对照医保科室)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Dept_Code { get; set; }

        /// <summary>
        /// 入院科室名称(对照医保科室)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Admit_Dept_Name { get; set; }

        /// <summary>
        /// 入院诊断编码(对照医保诊断)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Admit_Dise_Code { get; set; }

        /// <summary>
        /// 入院诊断名称(对照医保诊断)
        /// DataType=VARCHAR2
        /// 长度=150
        /// Nullable=1
        /// </summary>
        public string Admit_Dise_Name { get; set; }

        /// <summary>
        /// 入院床号
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Bed_No { get; set; }

        /// <summary>
        /// 入院医生编码(对照医保医生)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Doctor_Code { get; set; }

        /// <summary>
        /// 入院医生姓名(对照医保医生)
        /// DataType=VARCHAR2
        /// 长度=60
        /// Nullable=1
        /// </summary>
        public string Admit_Doctor_Name { get; set; }

        /// <summary>
        /// 医保住院交易号
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Admit_Trade_No { get; set; }

        /// <summary>
        /// 医保住院交易时间
        /// DataType=DATE
        /// Nullable=1
        /// </summary>
        public DateTime? Admit_Trade_Date { get; set; }

        /// <summary>
        /// 医保登记操作员
        /// DataType=VARCHAR2
        /// 长度=8
        /// Nullable=1
        /// </summary>
        public string Admit_Operid { get; set; }

        /// <summary>
        /// 生育小孩数
        /// DataType=NUMBER
        /// 精度=(1,0)
        /// Nullable=1
        /// </summary>
        public short? Birth_Babys { get; set; }

        /// <summary>
        /// 生育手术(对照医保手术)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Birth_Operation { get; set; }

        /// <summary>
        /// 生育并发症(对照医保诊断)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Birth_Comp { get; set; }

        /// <summary>
        /// 丈夫身份证号
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Husband_Idno { get; set; }

        /// <summary>
        /// 丈夫姓名
        /// DataType=VARCHAR2
        /// 长度=60
        /// Nullable=1
        /// </summary>
        public string Husband_Name { get; set; }

        /// <summary>
        /// 医保结算号(医保结算后,医保返回的)
        /// DataType=VARCHAR2
        /// 长度=30
        /// Nullable=1
        /// </summary>
        public string Settle_No { get; set; }

        /// <summary>
        /// 医保结算总费用
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Total_Money { get; set; }

        /// <summary>
        /// 医保结算现金支付金额
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Cash_Pay { get; set; }

        /// <summary>
        /// 基金支付金额
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Fund_Pay { get; set; }

        /// <summary>
        /// 个人帐户支付
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Account_Pay { get; set; }

        /// <summary>
        /// 公务员补助
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Civilservan_Subsidy { get; set; }

        /// <summary>
        /// 医疗救助金额
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Medicaid_Pay { get; set; }

        /// <summary>
        /// 大额支付
        /// DataType=NUMBER
        /// 精度=(18,4)
        /// Nullable=0
        /// </summary>
        public decimal Large_Pay { get; set; }

        /// <summary>
        /// 结算后账户余额
        /// DataType=NUMBER
        /// 精度=(12,2)
        /// Nullable=0
        /// </summary>
        public decimal Account_Balance { get; set; }

        /// <summary>
        /// 出院科室编码(对照医保科室)
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Dis_Dept_Code { get; set; }

        /// <summary>
        /// 出院科室名称(对照医保科室)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Dis_Dept_Name { get; set; }

        /// <summary>
        /// 出院诊断编码(对照医保诊断)
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Dis_Dise_Code { get; set; }

        /// <summary>
        /// 出院诊断名称(对照医保诊断)
        /// DataType=VARCHAR2
        /// 长度=150
        /// Nullable=1
        /// </summary>
        public string Dis_Dise_Name { get; set; }

        /// <summary>
        /// 出院日期
        /// DataType=DATE
        /// Nullable=1
        /// </summary>
        public DateTime? Dis_Date { get; set; }

        /// <summary>
        /// 医保结算交易号
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Settle_Trade_No { get; set; }

        /// <summary>
        /// 医保结算交易时间
        /// DataType=DATE
        /// Nullable=1
        /// </summary>
        public DateTime? Settle_Trade_Date { get; set; }

        /// <summary>
        /// 医保结算操作员
        /// DataType=VARCHAR2
        /// 长度=8
        /// Nullable=1
        /// </summary>
        public string Settle_Operid { get; set; }

        /// <summary>
        /// 扩展1
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Extend1 { get; set; }

        /// <summary>
        /// 扩展2
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Extend2 { get; set; }

        /// <summary>
        /// 扩展3
        /// DataType=VARCHAR2
        /// 长度=200
        /// Nullable=1
        /// </summary>
        public string Extend3 { get; set; }

        /// <summary>
        /// 扩展4
        /// DataType=VARCHAR2
        /// 长度=200
        /// Nullable=1
        /// </summary>
        public string Extend4 { get; set; }

        /// <summary>
        /// 扩展5
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Extend5 { get; set; }

        /// <summary>
        /// 入院登记卡类别
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Card_Type { get; set; }

        /// <summary>
        /// 入院登记卡号
        /// DataType=VARCHAR2
        /// 长度=50
        /// Nullable=1
        /// </summary>
        public string Card_No { get; set; }

        /// <summary>
        /// 状态
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Insur_Status { get; set; }

        /// <summary>
        ///
        /// DataType=VARCHAR2
        /// 长度=30
        /// Nullable=1
        /// </summary>
        public string Bill_Upload { get; set; }

        /// <summary>
        ///
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Dis_Way { get; set; }

        /// <summary>
        ///
        /// DataType=VARCHAR2
        /// 长度=20
        /// Nullable=1
        /// </summary>
        public string Admit_Way { get; set; }

        /// <summary>
        ///
        /// DataType=DATE
        /// Nullable=1
        /// </summary>
        public DateTime? Settle_Trade_Date_End { get; set; }

        /// <summary>
        /// 医保支付方式（结算清单上传用)
        /// </summary>
        public string Hi_Paymtd { get; set; }
    }

**Comment by shuxinqin** [comment]
trackentity针对更新，对于插入无效。

**Comment by yangzhinong** [comment]
我只是想更新 某几个列， Models.Insur_Visit_Record d = new Models.Insur_Visit_Record();
                d.Settle_No = "1231";
                d.Settle_Operid = "123";
                d.Account_Pay = 0m;
                d.Cash_Pay = 0m;
                d.Total_Money = 250.12m;
                d.Settle_Trade_Date = DateTime.Now;
                d.Settle_Trade_Date_End = DateTime.Now.AddMinutes(1);
                d.Insur_Status = "已核实";
                d.Account_Balance = 20;
                db.Update<Models.Insur_Visit_Record>(
                    x => x.Patient_Id == "10002000" && x.Visit_Id == 2,
                    x => d);
                db.Save(d);  这样也报错，是什么原因呢， 正确的写法是什么？  报错内容是：System.Exception:“Unhandled expression type: 'MemberAccess'”
    at Chloe.Core.Visitors.InitMemberExtractor.Visit(Expression exp) in D:\code\Chloe\src\Chloe\Core\Visitors\InitMemberExtractor.cs:line 32
   at Chloe.Core.Visitors.InitMemberExtractor.VisitLambda(LambdaExpression exp) in D:\code\Chloe\src\Chloe\Core\Visitors\InitMemberExtractor.cs:line 35
   at Chloe.Core.Visitors.InitMemberExtractor.Visit(Expression exp) in D:\code\Chloe\src\Chloe\Core\Visitors\InitMemberExtractor.cs:line 26
   at Chloe.Core.Visitors.InitMemberExtractor.Extract(Expression exp) in D:\code\Chloe\src\Chloe\Core\Visitors\InitMemberExtractor.cs:line 16
   at Chloe.DbContext.Update[TEntity](Expression`1 condition, Expression`1 content, String table) in D:\code\Chloe\src\Chloe\DbContext.cs:line 544
   at Chloe.DbContext.Update[TEntity](Expression`1 condition, Expression`1 content) in D:\code\Chloe\src\Chloe\DbContext.cs:line 535
   at ChloeOracleTest.Program.Main(String[] args) in D:\code\choleTest\ChloeOracleTest\Program.cs:line 55

**Comment by yangzhinong** [comment]
![image](https://user-images.githubusercontent.com/21005073/130800458-30f75b62-f133-4269-81d1-d5e93cfa6fec.png)

**Comment by yangzhinong** [comment]
插入 也是始

> trackentity针对更新，对于插入无效。

不要 trackentity 一样，插入参数不匹配 ！如下：
var d = db.Query<Models.Insur_Visit_Record>().FirstOrDefault();
d.Settle_No = "1231";
d.Settle_Operid = "123";
d.Account_Pay = 0m;
d.Cash_Pay = 0m;
d.Total_Money = 250.12m;
d.Settle_Trade_Date = DateTime.Now;
d.Settle_Trade_Date_End = DateTime.Now.AddMinutes(1);
d.Insur_Status = "已核实";
d.Account_Balance = 20;
db.Save(d);

**Comment by yangzhinong** [comment]
db.Update<Models.Insur_Visit_Record>(
x => x.Patient_Id == "10002000" && x.Visit_Id == 2,
x => d); 这种方式更报错： ：System.Exception:“Unhandled expression type: 'MemberAccess'”

**Comment by shuxinqin** [comment]
db.Update<Models.Insur_Visit_Record>(
x => x.Patient_Id == "10002000" && x.Visit_Id == 2,
x => new Insur_Visit_Record(){ xx  =xxxx });

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/wiki/Chloe.Extension 这里面有一些更新相关的扩展方法，可以参考

**Comment by yangzhinong** [comment]
INSERT INTO "YZN"."INSUR_VISIT_RECORD"("PATIENT_ID","VISIT_ID","INSUR_TYPE","INSUR_NO","CENTER_CODE","ADMIT_NO","ADMIT_INSUR_TYPE","ADMIT_MED_TYPE","ADMIT_DATE","ADMIT_DEPT_CODE","ADMIT_DEPT_NAME","ADMIT_DISE_CODE","ADMIT_DISE_NAME","ADMIT_BED_NO","ADMIT_DOCTOR_CODE","ADMIT_DOCTOR_NAME","ADMIT_TRADE_NO","ADMIT_TRADE_DATE","ADMIT_OPERID","BIRTH_BABYS","BIRTH_OPERATION","BIRTH_COMP","HUSBAND_IDNO","HUSBAND_NAME","SETTLE_NO","TOTAL_MONEY","CASH_PAY","FUND_PAY","ACCOUNT_PAY","CIVILSERVAN_SUBSIDY","MEDICAID_PAY","LARGE_PAY","ACCOUNT_BALANCE","DIS_DEPT_CODE","DIS_DEPT_NAME","DIS_DISE_CODE","DIS_DISE_NAME","DIS_DATE","SETTLE_TRADE_NO","SETTLE_TRADE_DATE","SETTLE_OPERID","EXTEND1","EXTEND2","EXTEND3","EXTEND4","EXTEND5","CARD_TYPE","CARD_NO","INSUR_STATUS","BILL_UPLOAD","DIS_WAY","ADMIT_WAY","SETTLE_TRADE_DATE_END","HI_PAYMTD") VALUES(:P_0,:P_1,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_3,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_3,:P_2,:P_4,:P_2,:P_2,:P_2,:P_2,:P_5,:P_6,:P_7,:P_7,:P_7,:P_7,:P_7,:P_7,:P_8,:P_2,:P_2,:P_2,:P_2,:P_3,:P_2,:P_9,:P_10,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_2,:P_11,:P_2,:P_2,:P_2,:P_12,:P_2)

**Comment by yangzhinong** [comment]
生成的参数完全不对。

**Comment by shuxinqin** [comment]
不对在哪？

**Comment by yangzhinong** [comment]
提示变量都已绑定，就如前面的截屏所示

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/wiki/Oracle-DbContext
修改 DbCommand 参数绑定方式
