### ISSUE TITLE
Sql server Insert时报错

### ISSUE THREAD

**Issue by distinct2010** [shuxinqin/Chloe#284]
{"Unable to get the id value from data reader."}

   at Chloe.SqlServer.MsSqlContext.<>c__DisplayClass21_0`1.<GetMapper>b__0(TEntity entity, IDataReader reader)
   at Chloe.SqlServer.MsSqlContext.<Insert>d__11`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](Task`1 task)
   at Chloe.DbContext.Insert[TEntity](TEntity entity, String table)
   at Chloe.DbContext.Insert[TEntity](TEntity entity)
   at NetPublicCloud.Service.LibraryService.SetBookClass(String strAction, BookClass bookClass, String& Err) in C:\Users\Administrator\source\repos\NetPublicCloud\NetPublicCloud.Service\LibraryService.cs:line 1444

**Comment by shuxinqin** [comment]
id 没设置为自增？

**Comment by distinct2010** [comment]
没有，id不是主键，是其他表的关联字段。insert时制定了id值

**Comment by shuxinqin** [comment]
论阅读文档的重要性：https://github.com/shuxinqin/Chloe/wiki/Annotations

**Comment by distinct2010** [comment]
[NonAutoIncrementAttribute]
        public int id { get; set; }   

这样吗？
