### ISSUE TITLE
生产系统运行一段时间后，频频抛出The connection is closed.错误，具体也无法定位到是哪儿块的代码抛出来的

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#311]
17:47:46.524  2 N - Chloe.Exceptions.ChloeException: An exception occurred while executing DbCommand. For details please see the inner exception. Invalid operation. The connection is closed.
 ---> System.InvalidOperationException: Invalid operation. The connection is closed.
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at Chloe.Data.AdoSession.ExecuteNonQuery(String cmdText, DbParam[] parameters, CommandType cmdType, Boolean async)
   --- End of inner exception stack trace ---
   at Chloe.Data.AdoSession.ExecuteNonQuery(String cmdText, DbParam[] parameters, CommandType cmdType, Boolean async)
   at Chloe.Data.InnerAdoSession.ExecuteNonQueryAsync(String cmdText, DbParam[] parameters, CommandType cmdType)
   at Chloe.Core.DbSession.ExecuteNonQueryAsync(String cmdText, CommandType cmdType, DbParam[] parameters)
   at Chloe.Core.DbSession.ExecuteNonQueryAsync(String cmdText, DbParam[] parameters)
   at Chloe.SqlServer.MsSqlContext.Update[TEntity](TEntity entity, String table, Boolean async)
17:48:55.982  2 N - Chloe.Exceptions.ChloeException: An exception occurred while executing DbCommand. For details please see the inner exception. Invalid operation. The connection is closed.

**Comment by zxingdream** [comment]
初步判断是 UpdateOnlyAsync 这个引起的
