### ISSUE TITLE
Does not support method 'Object.Equals(Object objA,Object objB)'

### ISSUE THREAD

**Issue by ragnaroks** [shuxinqin/Chloe#315]
`entity.Id` 和 `request.Id` 都是 `Int32`，且不小于 1，在此例中分别是 `16385` 和 `16385`，这个异常可能是什么原因导致？

```csharp
Boolean exist;
try {
    exist=databaseContext.Query<Account>(entity=>Sql.Equals(entity.Id,request.Id)).Any();
}catch(Exception exception){
    this.Logger.LogError(exception,"执行数据库查询异常");
    return this.Json(response);
}
```

```log
System.NotSupportedException: Does not support method 'Object.Equals(Object objA,Object objB)'.
    at Chloe.MySql.SqlGenerator.Visit(DbMethodCallExpression exp)
    at Chloe.MySql.SqlGenerator.BuildWhereState(DbExpression whereExpression)
    at Chloe.MySql.SqlGenerator.BuildGeneralSql(DbSqlQueryExpression exp)
    at Chloe.MySql.SqlGenerator.Visit(DbSqlQueryExpression exp)
    at Chloe.MySql.DbExpressionTranslator.Translate(DbExpression expression)
    at Chloe.Query.Internals.InternalQuery`1.GenerateCommandFactor()
    at Chloe.Query.Internals.InternalQuery`1.GetEnumerator()
    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
    at HttpApi.Controllers.AppController.CheckBind(DatabaseContext databaseContext, CheckBindRequest request) in D:\repo\HttpApi\Controllers\AppController.cs:line 0
```

**Comment by shuxinqin** [comment]
Sql.Equals 是支持的。你这个异常肯定不是 exist=databaseContext.Query<Account>(entity=>Sql.Equals(entity.Id,request.Id)).Any(); 这行代码引发的。
Object.Equals 确实是不支持，查看有没有使用 Object.Equals(Object objA,Object objB) 的地方

**Comment by ragnaroks** [comment]
调试确实是这个地方引发的异常，修改为 `Sql.Equals<Int32>(entity.Id,request.Id)` 后异常消失

**Comment by shuxinqin** [comment]
(⊙o⊙)…~有一种情况会出现你这个异常，可能是 entity.Id, request.Id 类型不一致，导致写法是 Sql.Equals，但实际调用了 Object.Equals 方法
确保  entity.Id, request.Id 类型一致就可以解决了
