### ISSUE TITLE
新版的MySql插入数据没问题，可是执行查询报错System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by bizhihai** [shuxinqin/Chloe#323]
MySql版本是：8.0.20.9
Chloe版本是：    
    Chloe.Extension：3.8.0
    Chloe.MySql：4.0.3

数据库连接符：Data Source = 127.0.0.1;Initial Catalog = adl_trans2;User Id = root;Password = 123456;Charset=utf8;
(去掉Charset也是一样报错。）

问题：按上面的配置，执行context.insert()没错，数据能正常插入数据库；可是执行任何的查询方法，无论是Query还是SqlQuery，都报下面的错：

`2022-07-05 14:07:28.4659|SiteApiV2.Controllers.TranArticleController|ERROR|  获取阅读记录出错 System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Chloe.Data.AdoSession.Activate()
   at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)
   at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
   at Chloe.Data.InnerAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
   at Chloe.Query.Internals.InternalQuery`1.<GetEnumerator>b__3_0(DbCommandFactor cmdFactor)
   at Chloe.Query.Internals.QueryEnumeratorCreator.QueryEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Chloe.Query.Query`1.ExecuteAggregateQuery[TResult](MethodInfo method, Expression argument, Boolean checkArgument)
   at Chloe.Query.Query`1.Count()
   at BUL.BLL.TranArticleService.Count(String userId, String keywords) in D:\Project\TxtToSpeed3\iReader\SiteApiV3.2\SiteApiV2\BUL\BLL\TranArticleService.cs:line 102
   at SiteApiV2.Controllers.TranArticleController.List(Object query) in D:\Project\TxtToSpeed3\iReader\SiteApiV3.2\SiteApiV2\Controllers\TranArticleController.cs:line 192`

之前以为是mysql编码问题，可是换了utf8mb4编码，也出现类型的报错。最早之前的mysql是没问题的，不知道是不是新版的mysql的问题。麻烦大神帮忙分析。

**Comment by shuxinqin** [comment]
这个驱动层的错误，没遇上过，我也无能为力了哦！
不过，请问这个错误是偶然出现的还是必然出现？

**Comment by bizhihai** [comment]
> 这个驱动层的错误，没遇上过，我也无能为力了哦！ 不过，请问这个错误是偶然出现的还是必然出现？

必然出现，只要执行查询，就报错，换oracle没问题，mysql插入数据也没问题

**Comment by shuxinqin** [comment]
换个MySqlConnector驱动试试

**Comment by bizhihai** [comment]
> 换个MySqlConnector驱动试试

解决了，把cholie.mysql和mysql.data都升级到最新版就可以了
