### ISSUE TITLE
 查询数据抛出异常

### ISSUE THREAD

**Issue by lld1995** [shuxinqin/Chloe#371]
System.ArgumentException: An item with the same key has already been added. Key: server=192.168.0.21;database=abcc;user id=root;password=*********;characterset=utf8;pooling=True;maxpoolsize=10;allowuservariables=True;sslmode=Disabled;allowpublickeyretrieval=True
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at MySql.Data.MySqlClient.MySqlPoolManager.GetPoolAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
         at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
         at MySql.Data.MySqlClient.MySqlConnection.Open()
         at System.Data.AdoExtension.Open(IDbConnection conn, Boolean async)
         at Chloe.Data.AdoSession.Activate(Boolean async)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior, Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](Task`1 task)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)
         at Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
         at Chloe.Data.InnerAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
         at Chloe.DbSessionProvider.ExecuteReader(String cmdText, CommandType cmdType, DbParam[] parameters)
         at Chloe.DbSessionProviderExtension.ExecuteReader(IDbSessionProvider dbSessionProvider, String cmdText, CommandType cmdType, DbParam[] parameters, Boolean async)
         at Chloe.Query.Internals.InternalQuery`1.<>c__DisplayClass7_0.<<GetFeatureEnumerator>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Chloe.Query.Internals.DataReaderEnumerator.MoveNext(Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](ValueTask`1 task)
         at Chloe.Query.Internals.DataReaderEnumerator.MoveNext()
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext(Boolean async)
         at Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](ValueTask`1 task)
         at Chloe.Query.Internals.QueryEnumerator`1.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Chloe.Query.Query`1.ToList()
         at Bll.StgApi.GetSymbol(Dictionary`2 retDic, SymbolType st, String key, Int32 pageNum, Int32 pageSize) in D:\LocalWorkSpaces\bian\Bll\StgApi.cs:line 42
         at apiServ.Controllers.ApiVisitorController.GetSymbol() in D:\LocalWorkSpaces\bian\apiServ\Controllers\ApiVisitorController.cs:line 192
         at lambda_method7(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by shuxinqin** [comment]
这个错误看起来是驱动抛出的的，用原生MySqlConnection对象验证下连接字符串正确与否吧

**Comment by lld1995** [comment]
> 这个错误看起来是驱动抛出的的，用原生MySqlConnection对象验证下连接字符串正确与否吧

正确的，是在偶然并发情况下发生的

**Comment by shuxinqin** [comment]
这个驱动抛出来的，得你自己去分析下原因咯
在并发下 MySql.Data 本身就有问题，试试换成MySqlConnector
